### ISSUE TITLE
Doesn't work with `oso: 0.10.0`

### ISSUE THREAD

**Issue by kvokov** [bjerkio/nestjs-oso#82]
Installed package versions:
```
"nestjs-oso": "1.2.0",
"oso": "0.10.0",
...
"@nestjs/common": "7.6.6",
"@nestjs/core": "7.6.6",
```

Errors:
```
node_modules/oso/dist/src/Polar.d.ts:1:10 - error TS2305: Module '"./Host"' has no exported member 'Host'.
1 import { Host } from './Host';
node_modules/oso/dist/src/Polar.d.ts:3:15 - error TS2305: Module '"./types"' has no exported member 'Class'.
3 import type { Class, Options, QueryResult } from './types';
```

But works fine with `"oso": "0.9.0"`

**Comment by gj** [comment]
The released version of `nestjs-oso` (1.2.0) has a peer dependency on Oso `^0.9.0`, which I'm guessing is the source of this issue. I can't even get `nestjs-oso@1.2.0` and `oso@0.10.0` installed unless I `--force` one of them 😄.

Nothing changed in the TypeScript library between 0.9.0 and 0.10.0 — we did a major version bump because [we fixed a rather obscure bug in the core](https://github.com/osohq/oso/blob/e5a730e6e4c438379816db2849a02f6a5e6f82ee/docs/changelogs/2021-01-20.rst#anonymous-rest-variables-now-properly-anonymized) that was still technically a breaking change. If you use Oso 0.9.0 for now (and don't write policies involving _multiple_ anonymous rest variables (`*_`) 😉), when @cobraz cuts a new release of `nestjs-oso` that includes the latest Oso version bump (#58), you'll be able to upgrade Oso from 0.9.0 -> 0.10.0 with zero code changes.

**Comment by audiBookning** [comment]
I am getting the same error with release 1.2.1.

I think that the problem is in the oso npm package releases after 0.9.0.
At the very least their .d.ts files are not correct.

As an example, you can see in the 0.10.1 version that the error `import { Host } from './Host';` in the Polar.d.ts file is triggered because Host.d.ts only has `export {};`

**Comment by gj** [comment]
@audiBookning thank you for noticing the difference in the generated `.d.ts` files! You are 100% correct. osohq/oso#702 should fix this issue. I'll post here once that's out.

**Comment by gj** [comment]
@audiBookning [0.10.2 is released](https://www.npmjs.com/package/oso/v/0.10.2) with fixed TypeScript .d.ts files 😄

**Comment by audiBookning** [comment]
Thank you.
I just tried the new version and everything seem to work fine from my side.
